version: '3.7'

x-default15:
  &default-odoo15
  tty: true
  build:
    context: ./configs/15.0
  volumes:
    - odoo15-web-data:/var/lib/odoo
    - ./configs/15.0/odoo.conf:/etc/odoo/odoo.conf
    - ./vendor/15.0:/mnt/vendor
    - ./.adminpasswd:/run/secrets/adminpasswd

x-default14:
  &default-odoo14
  tty: true
  build:
    context: ./configs/14.0
  volumes:
    - odoo14-web-data:/var/lib/odoo
    - ./configs/14.0/odoo.conf:/etc/odoo/odoo.conf
    - ./vendor/14.0:/mnt/vendor
    - ./.adminpasswd:/run/secrets/adminpasswd

x-default14b:
  &default-odoo14b
  tty: true
  build:
    context: ./configs/14.0b
  volumes:
    - odoo14-web-data:/var/lib/odoo
    - ./configs/14.0b/odoo.conf:/etc/odoo/odoo.conf
    - ./vendor/14.0:/mnt/vendor
    - ./.adminpasswd:/run/secrets/adminpasswd

x-default13:
  &default-odoo13
  tty: true
  build:
    context: ./configs/13.0
  volumes:
    - odoo13-web-data:/var/lib/odoo
    - ./configs/13.0/odoo.conf:/etc/odoo/odoo.conf
    - ./vendor/13.0:/mnt/vendor
    - ./.adminpasswd:/run/secrets/adminpasswd

x-default13e:
  &default-odoo13e
  tty: true
  build:
    context: ./configs/13.0e
  volumes:
    - odoo13-web-data:/var/lib/odoo
    - ./configs/13.0e/odoo.conf:/etc/odoo/odoo.conf
    - ./vendor/13.0:/mnt/vendor
    - ./.adminpasswd:/run/secrets/adminpasswd

x-default12:
  &default-odoo12
  tty: true
  build:
    context: ./configs/12.0
  volumes:
    - odoo12-web-data:/var/lib/odoo
    - ./configs/12.0/odoo.conf:/etc/odoo/odoo.conf
    - ./vendor/12.0:/mnt/vendor
    - ./.adminpasswd:/run/secrets/adminpasswd

x-default11:
  &default-odoo11
  tty: true
  build:
    context: ./configs/11.0
  volumes:
    - odoo11-web-data:/var/lib/odoo
    - ./configs/11.0/odoo.conf:/etc/odoo/odoo.conf
    - ./vendor/11.0:/mnt/vendor
    - ./.adminpasswd:/run/secrets/adminpasswd

x-default10:
  &default-odoo10
  tty: true
  build:
    context: ./configs/10.0
  volumes:
    - odoo10-web-data:/var/lib/odoo
    - ./configs/10.0/odoo.conf:/etc/odoo/odoo.conf
    - ./vendor/10.0:/mnt/vendor
    - ./.adminpasswd:/run/secrets/adminpasswd

services:
  web10:
    << : *default-odoo10
    depends_on:
      - db
      - longpolling10
    ports:
      - "10069:8069"

  longpolling10:
    << : *default-odoo10
    depends_on:
      - db
    command: ['odoo', 'gevent']
    ports:
      - "10072:8072"

  web11:
    << : *default-odoo11
    depends_on:
      - db
      - longpolling11
    ports:
      - "11069:8069"

  longpolling11:
    << : *default-odoo11
    depends_on:
      - db
    command: ['odoo', 'gevent']
    ports:
      - "11072:8072"

  web12:
    << : *default-odoo12
    depends_on:
      - db
      - longpolling12
    ports:
      - "12069:8069"

  longpolling12:
    << : *default-odoo12
    depends_on:
      - db
    command: ['odoo', 'gevent']
    ports:
      - "12072:8072"

  web13:
    << : *default-odoo13
    depends_on:
      - db
      - longpolling13
    ports:
      - "13069:8069"

  longpolling13:
    << : *default-odoo13
    depends_on:
      - db
    command: ['odoo', 'gevent']
    ports:
      - "13072:8072"

  web13e:
    << : *default-odoo13e
    depends_on:
      - db
      - longpolling13e
    ports:
      - "23069:8069"

  web13edebug:
    << : *default-odoo13e
    build:
      context: ./configs/13.0e
      dockerfile: Dockerfile.debug
    depends_on:
      - db
      - longpolling13e
      - wdb
    ports:
      - "23069:8069"
    environment:
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True
    command: ['--dev', 'reload']

  longpolling13e:
    << : *default-odoo13e
    depends_on:
      - db
    command: ['odoo', 'gevent']
    ports:
      - "23072:8072"

  web14:
    << : *default-odoo14
    depends_on:
      - db
      - longpolling14
    ports:
      - "14069:8069"

  longpolling14:
    << : *default-odoo14
    depends_on:
      - db
    command: ['odoo', 'gevent']
    ports:
      - "14072:8072"

  web14b:
    << : *default-odoo14b
    depends_on:
      - db
      - longpolling14b
    ports:
      - "14169:8069"

  longpolling14b:
    << : *default-odoo14b
    depends_on:
      - db
    command: ['odoo', 'gevent']
    ports:
      - "14172:8072"

  web15:
    << : *default-odoo15
    depends_on:
      - db
      - longpolling15
    ports:
      - "15069:8069"
    environment:
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True

  longpolling15:
    << : *default-odoo15
    depends_on:
      - db
    command: ['odoo', 'gevent']
    ports:
      - "15072:8072"
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  wdb:
    image: kozea/wdb:3.3.0
    ports:
      - "127.0.0.1:1984:1984"

volumes:
  odoo10-web-data:
  odoo11-web-data:
  odoo12-web-data:
  odoo13-web-data:
  odoo14-web-data:
  odoo15-web-data:
  odoo-db-data:
